name: caching_pipeline
on: push
jobs:
  build_npm:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: Cache Dependency
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        run: npm ci
      - name: npm build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: dist
  deploy_app:
    needs: build_npm
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "deploy application"
      - name: get code
        uses: actions/checkout@v6
      - name: Cache Dependency
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        run: npm ci