name: caching_pipeline
on: 
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MONGODB_CLUSTER_ADDRESS: devopsyug.i74utwt.mongodb.net
  MONGODB_USERNAME: db_user
  MONGODB_PASSWORD: test@123
  MONGODB_DB_NAME: devopsyug
  PORT: 8080
jobs:
  build_npm:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: Cache Dependency
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        run: npm ci
      - name: Run Tests
        run: npm start &npx wait-on http://127.0.0.1:$PORT
      - name: npm build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: dist
  deploy_app:
    needs: build_npm
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "deploy application"
      - name: get code
        uses: actions/checkout@v6
      - name: Cache Dependency
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        run: npm ci
      - name: Outputs Variables
        run: |
          echo "Mongo Username: ${{ env.MONGODB_USERNAME }}"
          echo "Mongo ClusterName: ${{ env.MONGODB_CLUSTER_ADDRESS }}"
          echo "Mongo DB_NAME: ${{ env.MONGODB_DB_NAME }}"