name: test_flow_3
on: push
jobs:
  build_npm:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
  deploy_app:
    needs: build_npm
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "deploy application"